### ISSUE TITLE
navigation error

### ISSUE THREAD

**Issue by vyaspranjal33** [pydelhi/blog#21]
clicking on "About Pydelhi" (http://bit.ly/pydelhi-intro) leads to following url "Site Not found" (http://bhanuvrat.github.io/pydelhi-intro/) which can be fixed by updating respective code in (https://github.com/pydelhi/blog/blob/gh-pages/category/general.html)

**Comment by codron95** [comment]
What's the correct url?

**Comment by mechanicnitin** [comment]
#21
On line 154 changed to "https://pydelhi.org/pydelhi-intro" instead of "http://bit.ly/pydelhi-intro" 
[general.txt](https://github.com/pydelhi/blog/files/2385919/general.txt)

**Comment by vyaspranjal33** [comment]
closing  this issue   Thanks @mechanicnitin  for sharing link fixed in #24

**Comment by realslimshanky** [comment]
@vyaspranjal33 the issue should only be closed when the Pull Request is merged.

**Comment by vyaspranjal33** [comment]
will take care from now onwards @realslimshanky :+1:
